# Generated by Django 5.1.4 on 2024-12-16 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="YouTube URL")),
                (
                    "format",
                    models.CharField(
                        choices=[("mp3", "Audio (MP3)"), ("mp4", "Video (MP4)")],
                        max_length=255,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Качество"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Задача на скачивание",
                "verbose_name_plural": "Задачи на скачивание",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="ID сессии"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия пользователя",
                "verbose_name_plural": "Сессии пользователей",
            },
        ),
        migrations.CreateModel(
            name="DownloadResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(max_length=500, verbose_name="Ссылка на файл"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Размер файла (в байтах)"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="api.downloadtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат скачивания",
                "verbose_name_plural": "Результаты скачивания",
            },
        ),
    ]
